version: "3"
services:
  reverseproxy:
      image: sofianechikhbled/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: sofianechikhbled/udacity-restapi-user
    environment:
      POSTGRESS_USERNAME: postgres
      POSTGRESS_PASSWORD:  lasauce2425
      POSTGRESS_DB: udagramkb 
      POSTGRESS_HOST: udagramkb.cq0kyil7ibhw.us-east-2.rds.amazonaws.com 
      AWS_REGION: us-east-2
      AWS_PROFILE: default
      AWS_BUCKET: udagramkb
      JWT_SECRET: helloworld
      URL: "http://localhost:8100"
  backend-feed:
    image: sofianechikhbled/udacity-restapi-feed
    volumes:
      - C:\Users\Sofiane\.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: postgres
      POSTGRESS_PASSWORD: lasauce2425  
      POSTGRESS_DB: udagramkb  
      POSTGRESS_HOST: udagramkb.cq0kyil7ibhw.us-east-2.rds.amazonaws.com 
      AWS_REGION: us-east-2
      AWS_PROFILE: default 
      AWS_BUCKET: udagramkb
      JWT_SECRET: helloworld
      URL: "http://localhost:8100"
  frontend:
    image: sofianechikhbled/udacity-frontend:local
    ports:
      - "8100:80"
